language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fglrx opencl-headers opencl-dev libgl1-mesa-dev
script:
  - make oclInfo
  - ls /etc/OpenCL/vendors
  - cat /etc/OpenCL/vendors/nvidia.icd
  - sudo bash -c "echo libamdocl64.so > /etc/OpenCL/vendors/amdocl64.icd"
  - rm /etc/OpenCL/vendors/nvidia.icd
  - cat /etc/OpenCL/vendors/amdocl64.icd
  - ./oclInfo
