language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fglrx fglrx-dev opencl-headers devscripts
script:
  - make oclInfo
  - ls /etc/OpenCL/vendors
  - apt-cache madison fglrx
  - rmadison fglrx
  - ./oclInfo
