language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fglrx fglrx-dev opencl-headers
script:
  - make oclInfo
  - ls /etc/OpenCL/vendors
  - ./oclInfo
