language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fglrx fglrx-core opencl-headers opencl-dev libgl1-mesa-dev
script:
  - make oclInfo
  - ./oclInfo
